version: '3.3'

x-env: &env
  DATABASE_URL: postgresql+psycopg2://test:test@db:5432/postgres
  REDIS_URL: redis://redis:6379/0
  MAILGUN_DOMAIN: ${MAILGUN_DOMAIN}
  MAILGUN_TOKEN: ${MAILGUN_TOKEN}

services:
  db:
    image: postgres:9.6
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  migrate:
    build: .
    command: sh -c 'until pg_isready -h db; do sleep 1; done && flask db upgrade'
    working_dir: /app/api
    environment:
      <<: *env
    volumes:
      - ./api/migrations:/app/api/migrations
    depends_on:
      - db

  api:
    build: .
    command: gunicorn "api.app:create_app()" --bind 0.0.0.0:3000
    environment:
      <<: *env
    ports:
      - "3000:3000"
    depends_on:
      - migrate
      - redis

  worker:
    build: .
    command: rq worker -u redis://redis:6379/0 emails
    environment:
      <<: *env
    depends_on:
      - redis
      - migrate

volumes:
  data:
