"""empty message

Revision ID: 46231e91ce9a
Revises: 215c0c333803
Create Date: 2023-02-22 21:39:21.878117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46231e91ce9a'
down_revision = '215c0c333803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
